package com.study.dao;

import com.study.domain.Opencount;

public interface OpencountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opencount
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opencount
     *
     * @mbggenerated
     */
    int insert(Opencount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opencount
     *
     * @mbggenerated
     */
    int insertSelective(Opencount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opencount
     *
     * @mbggenerated
     */
    Opencount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opencount
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Opencount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opencount
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Opencount record);
}